name: Report artifacts
on:
  check_suite:
    types: [requested, completed]

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    name: Report Artifacts
    steps:
    - uses: actions/checkout@v1
    - name: debug
      env:
        JOB_CONTEXT: ${{ toJson(github }}
        STEP_CONTEXT: ${{ toJson(steps}}
        RUNNER_CONTEXT: ${{ toJson(runner}}
      run: env
