name: Artifacts
on:
  check_suite:
    types: [requested, completed]
  issue_comment:
    types: [created]

jobs:
  report_artifacts:
    runs-on: ubuntu-latest
    name: Report Artifacts
    steps:
    - uses: actions/checkout@v1
    - name: debug
      env:
        JOB_CONTEXT: ${{ toJson(github) }}
      run: env && git branch
